prisma/schema.prisma
=> Specifying binary targets in Prisma schema config

package-lock.json, package.json
Knex, SQL builder library removed because it replaced by Prisma
QPA-15
=> build: :heavy_minus_sign: Knex removed

lib/thread.ts, package-lock.json, package.json, services/app.module.ts, services/applicationContext.ts, services/prometeo/dtos/list-suppliers-item.dto.ts, services/prometeo/encore.service.ts, services/prometeo/prometeo.controller.ts, services/prometeo/prometeo.module.ts, services/prometeo/prometeo.service.ts, services/prometeo/types/supplier.ts
I also made a Redis integration with exponential backoff in case the request to Prometeo API just fails.
Closes QPA-43
https://qompa.atlassian.net/browse/QPA-43
Retrieve, store in cache and expose information about suppliers of Prometeo API.
=> Endpoint to retrieve suppliers from Prometeo API

services/prometeo/prometeo.service.ts
Related to [QPA-41](https://qompa.atlassian.net/browse/QPA-41) and [QPA-43](https://qompa.atlassian.net/browse/QPA-43).
It seems that every endpoint that pretends to integrate with this provider will need to have this mechanism because their endpoints(at least in sandbox environment) are not fault-tolerant.
[QPA-41]: …
=> Prometeo request config

services/prometeo/prometeo.controller.ts, services/prometeo/prometeo.service.ts, services/prometeo/types/prometeo-api.ts
Blocks [QPA-40](https://qompa.atlassian.net/browse/QPA-40) and [QPA-38](https://qompa.atlassian.net/browse/).
Related to [QPA-42](https://qompa.atlassian.net/browse/QPA-42?atlOrigin=eyJpIjoiNGIzMTdmNzdiMjBhNDMzOTgwZDM5OTg5YzE5YjY5NTEiLCJwIjoiaiJ9).
Integrate the login endpoint from the Prometeo API with flexible retries.
[QPA-40]: …
=> Prometeo Login wtih Fault tolerance

package.json, prisma/schema.prisma
Better being clear with each database URL connection
Given from now we gonna use Mongo and Postgres is better being clear with each database URL connection: 
- 🤔 (`:thinking:`) or 💭 …
=> ci: :green_heart: Postgres url env variable renamed

services/prometeo/prometeo.controller.ts, services/prometeo/validators/prometeo-api.ts
Improve validations in payload fields of every endpoint that calls the Prometeo API
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could …
=> Prometeo API service: added more validations in request payload

package-lock.json, package.json
Upgrade encore to the latest version
- 🎨 (`:art:`) …
=> Upgraded encore version to v1.41.4

.envrc
Automatically load environment variables from my `.env` file to my current shell session.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and …
=> .envrc: load .env files

services/prometeo/prometeo.controller.ts, services/prometeo/types/prometeo-api.ts
Improve the current API documentation for the Prometeo service.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from …
=> Doc comments for Prometeo's API documentation

prisma/schema.prisma, services/app.module.ts, services/applicationContext.ts, services/banking/banking.controller.ts, services/banking/banking.module.ts, services/banking/banking.service.ts, services/banking/dtos/setup-provider.dto.ts, services/banking/encore.service.ts, services/banking/service-errors.ts, services/banking/types/prometeo-credentials.ts, services/banking/types/response.ts, services/banking/validators/setup-provider-access.ts, services/prometeo/types/provider.ts
Closes [QPA-67](https://qompa.atlassian.net/browse/QPA-67)
Store and encrypt credentials to use with Prometeo API provider
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not …
=> QPA-67: Bank account credentials encryption

package-lock.json, package.json
=> Upgraded encore version

.gitignore, package.json
Trying to build Prisma client just after npm install in the ci
Deploy in Encore works, getting connected.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a …
=> Backend by environments

package-lock.json, package.json
=> Upgraded encore at v1.41.7

package-lock.json
Looking for check if make prisma generate just after npm installl help to make ci works.
Make prima generate script execute 
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's …
=> chore: :package: postinstall script

prisma/schema.prisma
=> Prisma fix: Updated data type for size column of organizations table

services/sunat/sunat.controller.ts
=> SUNAT: added debug logs for endpoint to retrieve rubros

services/organizations/dtos/create-organization.dto.ts, services/organizations/organization.controller.ts, services/organizations/organizations.service.ts, services/organizations/service-errors.ts
=> Organization service: improvements in error handling and logs

.vscode/launch.json, package-lock.json
Run project under debugging through VSCode
- 🎨 …
=> chore: launch file to debuging added

services/prometeo/prometeo.service.ts, services/prometeo/types/prometeo-api.ts
Including the provider bcp_pers_pe from prometeo to cover enterprise accounts powered by viaBCP platform
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed …
=> feat: :sparkles: Prometeo viaBCP included

package-lock.json
=> Little package-lock.json update due to update in encore's license

services/auth/authHandler.ts
=> Error boundary for authentication middleware

services/sunat/sunat.controller.ts
=> Sunat: Error boundary for endpoint search entity information by RUC

package-lock.json
=> package-lock: Little update in Encore's license

lib/clerk.ts, services/banking/banking.controller.ts, services/banking/banking.service.ts, services/banking/service-errors.ts, services/banking/types/prometeo-credentials.ts, services/banking/types/response.ts, services/prometeo/prometeo.service.ts
=> Improvements in banking service

package-lock.json, package.json
=> Upgraded encore at v1.41.8

prisma/schema.prisma, services/banking/banking.controller.ts, services/banking/banking.service.ts, services/banking/service-errors.ts, services/banking/types/response.ts, services/prometeo/prometeo.controller.ts, services/prometeo/prometeo.service.ts, services/prometeo/types/prometeo-api.ts, services/prometeo/validators/prometeo-api.ts
=> Iimprovements in banking service

prisma/schema.prisma, services/banking/banking.controller.ts, services/banking/banking.service.ts, services/banking/dtos/setup-provider.dto.ts, services/banking/types/banking-directory.ts, services/banking/types/response.ts
=> Banking: support for names and updated_at created_at fields for banking directories

services/prometeo/prometeo.service.ts
=> Prometeo: passing empty branch parameter to endpoint to preprocess payment

package-lock.json, package.json
=> Updated encore at version 1.41.10

services/banking/banking.controller.ts, services/banking/banking.service.ts, services/banking/dtos/preprocess-transfer.dto.ts, services/prometeo/prometeo.controller.ts, services/prometeo/prometeo.service.ts, services/prometeo/types/prometeo-api.ts, services/prometeo/types/response.ts, services/prometeo/types/transference.ts
Among these improvements there is the full support for transfers! :)
I have to say that still there's a lot of work to do in error handling and user scenarios that might happen anytime.
In the following screen captures we've proven that we're able to perform banking transferences from the Prometeo API provider identified as **bcp_pers_pe** for destination accounts in Interbank and BCP, even exchanging money.
- Updated any necessary documentation …
=> More improvements in banking service

services/banking/banking.controller.ts
=> Removed comments about goals in banking module

tsconfig.json
=> TSConfig: enabled option to forbid unused locals

services/banking/banking.controller.ts, services/banking/banking.service.ts, services/banking/dtos/setup-directory.dto.ts, services/banking/types/banking-directory.ts, services/banking/types/request.ts, services/banking/types/response.ts, services/banking/validators/request.ts, services/banking/validators/setup-directory.ts, services/prometeo/types/transference.ts
This does not include the use cases and improved error handling that I mentioned before.
it contains some internal refactorings to enhance the micro-service maintainability.
- 🤔 (`:thinking:`) or 💭 …
=> Mooore improvements in banking service

services/banking/banking.controller.ts, services/banking/dtos/preprocess-transfer.dto.ts, services/banking/types/response.ts
=> [refactor] Banking: moved preprocess transfer response dto in its corresponding file

services/banking/banking.service.ts, services/prometeo/interfaces/get-clients-response.interface.ts, services/prometeo/prometeo.controller.ts, services/prometeo/prometeo.service.ts, services/prometeo/types/prometeo-api.ts, services/prometeo/types/request.ts, services/prometeo/types/response.ts, services/prometeo/validators/prometeo-api.ts
=> Improvements in Prometeo service

package-lock.json, package.json
=> chore: upgraded encore to v1.41.11

package-lock.json, package.json
=> chore: upgraded encore to v1.41.12

package-lock.json, package.json
=> chore: upgraded encore to v1.41.14

services/app.module.ts, services/applicationContext.ts, services/third-party/encore.service.ts, services/third-party/service-errors.ts, services/third-party/third-part.module.ts, services/third-party/truora.controller.ts, services/third-party/truora.module.ts, services/third-party/truora.service.ts, services/third-party/types/response.ts, services/third-party/types/truora/response.ts
=> Third party - Truora: added endpoint to allow client to create api key to verify identity

services/prometeo/types/request.ts
=> Prometeo: exporting `PrometeoSessionKeyHeader` in order to fix TS4023

package-lock.json, package.json
=> Encore upgraded to v1.42.0

services/third-party/truora.controller.ts
=> Third party/truora: all countries are allowed in token to perform identity verification

services/third-party/truora.controller.ts, services/third-party/truora.service.ts, services/third-party/types/request.ts, services/third-party/types/response.ts, services/third-party/types/truora/process.ts, services/third-party/types/truora/request.ts, services/third-party/types/truora/response.ts
=> Third party/truora: endpoint that integrates with Truora service to get process result by ID

package-lock.json, package.json
=> Upgraded encore to v1.41.12

services/third-party/truora.controller.ts, services/third-party/types/request.ts
=> Truora: added payload param to specify platform in endpoint to issue new identity verification

services/organizations/organization.controller.ts, services/organizations/organizations.service.ts, services/organizations/service-errors.ts, services/organizations/types/request.ts, services/organizations/types/response.ts
=> Organizations: added API service to search user's organization

prisma/schema.prisma, services/sunat/service-errors.ts, services/sunat/sunat.controller.ts, services/sunat/sunat.service.ts
=> SUNAT: Verifying SOL credentials with SUNAT's OAuth2 verification + users can have multiple organizations so then more than one sunat profile

.github/auto_assign.yml, .github/workflows/pr-setup.yml
=> CI: Automatic PR setup

services/banking/banking.service.ts
=> Banking: Fixed TS errors when performing API calls to Prometeo microservices

services/users/helpers/serializable.ts, services/users/interfaces/serializable-user.interface.ts, services/users/types/request.ts, services/users/users.controller.ts
=> Users: using snake case for API params and response

services/users/users.service.ts
=> Users: terms and privacy agreeements are updated in requester's Clerk user

services/users/types/request.ts
=> Users: all parameters to update an user are optional

services/banking/banking.controller.ts, services/banking/banking.service.ts, services/banking/types/response.ts, services/sunat/service-errors.ts, services/sunat/sunat.controller.ts, services/sunat/sunat.service.ts, services/sunat/types/response.ts, services/users/types/response.ts, services/users/types/status.ts, services/users/users.controller.ts, services/users/users.service.ts
=> QPA-123: added enpdoint to check user status

services/users/users.service.ts
=> Fix: fixed API call of endpoint to check user status

package-lock.json, package.json
=>  Upgraded encore at v1.42.4

services/banking/banking.controller.ts
=> Refactor(banking): renamed endpoint name to list directories for Encore

services/banking/banking.controller.ts, services/banking/banking.service.ts, services/banking/types/request.ts, services/banking/types/response.ts
=> Banking: added endpoint to delete directory by ID
